
production:
  adapter: postgresql
  database: ToDo_production
  username: postgres
  password:

test:
  adapter: postgresql
  database: ToDo_test
  username: postgres
  password: 

development:
  adapter: postgresql
  database: ToDo_development
  username: postgres
  password: 
