login: &login
  adapter: postgresql
  host: localhost
  username: salva
  password:
  encoding: UTF-8 

development:
  database: salva_dev
  <<: *login

test: 
  database: salva_test
  <<: *login

production:
  adapter: postgresql
  database: salva
  host: siesta.fisica.unam.mx
  username: alex
  password:
  encoding: UTF-8
