institution: Instituto de Física - UNAM
institution_url: http://www.fisica.unam.mx
administrative_key: 314
theme: default 
most_common_school: 14
educational_institutiontitles: Academia, Centro, Colegio, Departamento, Escuela, Facultad, Instituto, Museo, Observatorio, Plantel, Programa, Universidad, Unidad
initial_group: default
permissions:
 default: *
 researcher: *
 academic_technician: *
 admin: *
most_common_finnancingsources: Dirección General de Asuntos del Personal Académico, Consejo Nacional de Ciencia y Tecnología