# General configuration for salva 
institution: Instituto de Física - UNAM
institution_url: http://www.fisica.unam.mx
administrative_key: 314
theme: fisica 
 
# Customizations for your institute, school, et.al
most_common_school: 14
educational_institutiontitles: Academia, Centro, Colegio, Departamento, Escuela, Facultad, Instituto, Museo, Observatorio, Plantel, Programa, Universidad, Unidad, Dirección
most_common_finnancingsources: Dirección General de Asuntos del Personal Académico, Consejo Nacional de Ciencia y Tecnología

# Groups and permissions
initial_group: default
permissions:
 default: *
 researcher: *
 academic_technician: *
 admin: *

# Technical support information
technical_support:
 unit: Secretaría Técnica de Cómputo
 person: Alejandro Juarez Robles
 address: Cub. 254, Edificio Principal del Instituto de Fisica -UNAM
 phone: 56 22 50 01 ext 289
 email: alex@fisica.unam.mx
 other_info: .
