---
- profile
- - general
  - - person
    - address
    - citizen
    - people_identification
- - schooling
  - jobposition
  - - jobposition_internal
    - - jobposition_at_institution
      - user_adscription
      - jobposition_log
    - jobposition_external
  - user_stimulus
  - updating_current_skills
  - - user_course
    - userconference
    - acadvisit
  - user_grant
  - membership
  - user_prize
  - user_language
  - user_skill
  - user_settings
  - - change_password
    - user_setting
- publications
- - book

  
