---
- profile
- - general
  - - person
    - address
    - citizen
    - people_identification
  - schooling
  - jobposition
  - - jobposition_internal
    - - jobposition_at_institution
      - user_adscription
      - jobposition_log
    - jobposition_external
  - user_stimulus
  - updating_current_skills
  - - user_course
    - userconference
    - acadvisit
  - user_schoolarship
  - membership
  - user_prize
  - user_language
  - user_skill
  - user_settings
  - - change_password
    - user_setting
- user_researchline
- publications
- - books
  - - bookedition_roleinbook
    - chapterinbook_roleinbook
  - refereedpubs
  - - user_article
    - user_inproceeding_refereed
  - reports
  - - user_techreport
    - user_techreport_internal
  - user_inproceeding_unrefereed
- other
- - user_journal
  - user_proceeding_refereed
  - user_proceeding_unrefereed


