---
- general
- - person
  - address
  - citizen
  - people_identification
- schooling
- user_as_student
- - user_as_student_project
  - user_as_student_thesis
  - user_as_student_advice
- user_schoolarship
- user_language
- user_reports
- - student_probatory_document
  - student_association_request
  - student_activities_report

