---
- profile
- - general
  - - person
    - address
    - citizen
    - people_identification
  - schooling
  - jobposition
  - - jobposition_internal
    - - jobposition_at_institution
      - user_adscription
      - jobposition_log
    - jobposition_external
  - user_stimulus
  - updating_current_skills
  - - user_course
    - userconference
    - acadvisit
  - user_schoolarship
  - membership
  - user_prize
  - user_language
  - user_skill
  - user_settings
  - - change_password
    - user_setting
- user_project
- user_researchline
- conferences_and_seminaries
- - user_technicalconferencetalk
  - user_seminary
- publications
- - books
  - - bookedition_roleinbook
    - chapterinbook_roleinchapter
  - refereedpubs
  - - user_article
    - user_inproceeding_refereed
  - reports
  - - user_techreport
    - user_techreport_internal
  - user_inproceeding_unrefereed
  - student_thesis
- scientific_spreading
- - user_newspaperarticle
  - user_conferencetalk
- colaboration_on_publications
- - user_journal
  - user_proceeding_refereed
- human_resources_formation_and_teaching
- - human_resources_formation
  - - user_thesis
    - thesis_juror
    - thesis_committee
  - teaching
  - - user_regularcourse
  - - user_specialcourse
- other_activities_or_products
- - userconference_committee
  - activity
  - user_genericwork
