---
- profile
- - general
  - - personal
    - address
    - user_personalids
    - user_citizens
  - schooling
  - user_jobpositions
  - user_stimulus
  - user_grants
- science_and_tech_production
- - publications
  - - book
