# Personal Information
- fullname: Person.find(@user.id).fullname
# Cites information
- author_name: UserCite.find(:first, :conditions => 'user_id = ' + @user.id.to_s).author_name
- total_cites: UserCite.find(:first, :conditions => 'user_id = ' + @user.id.to_s).total
# Address and contact information
- email: User.find(@user.id).email
# Jobposition at institution log
- worker_key: Finder.new(JobpositionLog, :first, :attributes => %w(worker_key), :conditions => 'user_id = ' + @user.id.to_s).as_text.first
- academic_years: Finder.new(JobpositionLog, :first, :attributes => %w(academic_years), :conditions => 'user_id = ' + @user.id.to_s).as_text.first
- administrative_years: Finder.new(JobpositionLog, :first, :attributes => %w(administrative_years), :conditions => 'user_id = ' + @user.id.to_s).as_text.first
# Most recent job at institution and most recent adscription
# most_recent_jobposition_at_institution: Finder.new(Jobposition, :first, :attributes => %w(jobpositioncategory institution startyear endyear), :conditions => '(institutions.institution_id = 1 OR institutions.id = 1) AND jobpositions.institution_id = institutions.id AND jobpositions.user_id = ' +@user.id.to_s, :order => 'jobpositions.startyear DESC' ).as_text.first
- most_recent_jobposition_at_institution: Finder.new(Jobposition, :first, :attributes => [['jobpositioncategory', 'roleinjobposition', 'jobpositionlevel'], 'institution', 'startyear'], :conditions => 'jobpositions.user_id = ' + @user.id.to_s, :order => 'jobpositions.startyear DESC' ).as_text.first
- most_recent_user_adscription: Finder.new(UserAdscription, :first, :attributes => ['adscription'], :conditions => 'user_adscriptions.user_id = ' + @user.id.to_s, :order => 'user_adscriptions.startyear DESC').as_text.first
- user_incharge: @user.user_incharge.person.fullname
